name: Python Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.5  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Si tienes pruebas unitarias

      - name: Login to Docker Hub 
        uses: docker/login-action@v2 #Este paso usa la acción docker/login-action@v2 para autenticarte en Docker Hub.
        with:
          username: ${{ secrets.DOCKER_USERNAME }} #Usa las credenciales configuradas desde git actions para acceder a Docker
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/interfaz-app-1:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/interfaz-app-1:latest

      - name: Run Flask app
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/interfaz-app-1:latest
